### ISSUE TITLE
Compiler errors

### ISSUE THREAD

**Issue by speige** [lep/lua2jass#2]
I don't know haskell, so forgive me if I did something stupid

Compiler\Lua.hs:163:13: error: [GHC-88464]
    Variable not in scope:
      when :: Bool -> CompileM () -> StateT S (Writer Asm) a4
    |
163 |             when emitLeave $
    |             ^^^^

Compiler\Lua.hs:202:9: error: [GHC-88464]
    Variable not in scope:
      forM_
        :: [(a2, Int -> StateT S (Writer Asm) a9)]
           -> ((a3, Int -> StateT S (Writer Asm) b1)
               -> StateT S (Writer Asm) b1)
           -> StateT S (Writer Asm) ()
    |
202 |         forM_ (zip [1..] fs) $ \(idx, f) -> do
    |         ^^^^^

Compiler\Lua.hs:209:9: error: [GHC-88464]
    Variable not in scope:
      forM_
        :: [(a0, Int -> StateT S (Writer Asm) a9)]
           -> ((a1, Int -> StateT S (Writer Asm) b0)
               -> StateT S (Writer Asm) b0)
           -> StateT S (Writer Asm) ()
    |
209 |         forM_ (zip [1..] fs) $ \(idx, f) -> do
    |         ^^^^^

Compiler\Lua.hs:243:19: error: [GHC-88464]
    Variable not in scope: void :: CompileM B.Register -> CompileM ()
    |
243 |     FunCall fc -> void $ compileFunCall fc
    |                   ^^^^

Compiler\Lua.hs:249:9: error: [GHC-88464]
    Variable not in scope:
      forM_ :: [Name] -> (Name -> CompileM ()) -> CompileM ()
    |
249 |         forM_ names $ \(Name name) ->
    |         ^^^^^

Compiler\Lua.hs:253:9: error: [GHC-88464]
    Variable not in scope: void :: CompileM () -> CompileM ()
    |
253 |         void $ compileAssign' (emit . B.Local) (map VarName names) exps
    |         ^^^^

Compiler\Lua.hs:333:9: error: [GHC-88464]
    Variable not in scope:
      forM_
        :: [Name] -> (Name -> CompileM ()) -> StateT S (Writer Asm) a5
    |
333 |         forM_ names $ \(Name name) ->
    |         ^^^^^

Compiler\Lua.hs:498:30: error: [GHC-88464]
    Variable not in scope:
      foldM
        :: ((B.Register, Text)
            -> Name -> StateT S (Writer Asm) (Int, Text))
           -> (Int, Text)
           -> [Name]
           -> StateT S (Writer Asm) (B.Register, Text)
    Suggested fix:
      Perhaps use one of these:
        `Map.fold' (imported from Data.Map),
        `Set.fold' (imported from Data.Set),
        `foldl' (imported from Prelude)
    |
498 |         (u, internalName) <- foldM `flip` (r0, t) `flip` init ns $ \(r0, name) (Name n) -> do
    |                              ^^^^^

Compiler\Lua.hs:533:30: error: [GHC-88464]
    Variable not in scope:
      foldM
        :: ((B.Register, Text)
            -> Name -> StateT S (Writer Asm) (Int, Text))
           -> (Int, Text)
           -> [Name]
           -> StateT S (Writer Asm) (B.Register, Text)
    Suggested fix:
      Perhaps use one of these:
        `Map.fold' (imported from Data.Map),
        `Set.fold' (imported from Data.Set),
        `foldl' (imported from Prelude)
    |
533 |         (u, internalName) <- foldM `flip` (r0, t) `flip` ns $ \(r0, name) (Name n) -> do
    |                              ^^^^^

Compiler\Lua.hs:740:9: error: [GHC-88464]
    Variable not in scope:
      forM_
        :: [(a7, Name)]
           -> ((B.Register, Name) -> StateT S (Writer Asm) ())
           -> StateT S (Writer Asm) a8
    |
740 |         forM_ (zip [1..] args) $ \(param, Name arg) -> do
    |         ^^^^^

Compiler\Lua.hs:743:9: error: [GHC-88464]
    Variable not in scope:
      when
        :: Bool -> StateT S (Writer Asm) () -> StateT S (Writer Asm) a6
    |
743 |         when isVararg $ do
    |         ^^^^
Error: cabal.exe: Failed to build exe:lua2jass from lua2jass-0.1.0.0.

**Comment by lep** [comment]
Sounds like some different GHC updates. I can check more in-depth later but something like `import Control.Monad` should do the trick. It's good style anyways so i will probably later commit that myself.

**Comment by lep** [comment]
Try 42b8a2d70b3f4f15684ee7586e15b3f716202360

**Comment by speige** [comment]
That worked great. Thanks!
